src/main/java/de/retest/recheck/cli/PreCondition.java
src/main/java/de/retest/recheck/cli/subcommands/Commit.java
src/main/java/de/retest/recheck/cli/subcommands/Diff.java
src/main/java/de/retest/recheck/cli/subcommands/Ignore.java

Make sure recheck can only be executed inside a project

---

ci/script.sh

See https://community.sonarsource.com/t/travis-plugin-is-failing-on-external-pull-request/807/3.

Add SonarCloud workaround for external PRs

---

README.md

Not 6 weeks since #78, but we now have mor than 100 downloads for the CLI. I think that's worth showing?

Add total downloads to readme

---

.mergify.yml

Repository rules doesn't seem to be accounted for bots.
*Before submission, please check that ...*
> TL;DR

Split rebase/merge and delete

---

CODE_OF_CONDUCT.md

to have one central code of conduct

Delegate to the retest docs

---

CHANGELOG.md
src/main/java/de/retest/recheck/cli/subcommands/Ignore.java
src/test/java/de/retest/recheck/cli/subcommands/CommitIT.java
src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
src/test/java/de/retest/recheck/cli/testutils/TestReportCreator.java

Fix ignore inserted deleted

---

src/main/java/de/retest/recheck/cli/subcommands/Ignore.java

*Before submission, please check that ...*
Related to Feature/delete deprecated methods #540 in recheck
> TL;DR

Substitude deprecated getAttributeDifferences with TestReportFilter

---

.mergify.yml

See: https://github.com/retest/recheck/pull/579/

Consider requested changes

---

src/main/java/de/retest/recheck/cli/utils/WarningUtil.java

Remove the dependency to LogUtil

---

pom.xml

~Due to some deploying errors, this is not available in central or github releases yet, and thus is provided through jitpack~ Travis finally decided to pass

Bumb recheck version to 1.9.0

---

CHANGELOG.md

What should we do with this?
1. Leave it empty
2. Add entry: Updated recheck version to 1.9.0

Finalize changelog for release 1.9.0

---

src/test/java/de/retest/recheck/cli/subcommands/CommitIT.java
src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
src/test/java/de/retest/recheck/cli/subcommands/IgnoreIT.java
src/test/java/de/retest/recheck/cli/subcommands/ShowIT.java

> Suggestion to reduce boilerplate code in tests 
see https://picocli.info/#execute

Tests: Reduce boilerplate code by using recommended command call

---

CHANGELOG.md
src/main/java/de/retest/recheck/cli/subcommands/Commit.java
src/main/java/de/retest/recheck/cli/subcommands/Completion.java
src/main/java/de/retest/recheck/cli/subcommands/Diff.java
src/main/java/de/retest/recheck/cli/subcommands/Ignore.java
src/main/java/de/retest/recheck/cli/subcommands/Migrate.java
src/main/java/de/retest/recheck/cli/subcommands/account/Logout.java
src/main/java/de/retest/recheck/cli/subcommands/account/Show.java

*Before submission, please check that ...*
The sub-commands should now use exit codes that are hopefully more in line with what a user might expect.
All done.

Report exit codes for all relevant sub-commands

---

pom.xml

> Add directly used dependencies to pom.xml 
and remove declared unused dependencies
WIP
http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

Add directly used dependencies to pom.xml

---

CHANGELOG.md
src/main/java/de/retest/recheck/cli/subcommands/Diff.java
src/main/java/de/retest/recheck/cli/subcommands/Show.java
src/main/resources/logback.xml
src/test/java/de/retest/recheck/cli/subcommands/CommitIT.java
src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
src/test/java/de/retest/recheck/cli/subcommands/IgnoreIT.java
src/test/java/de/retest/recheck/cli/utils/SystemInUtilTest.java

> Suggestion to change logger pattern and formatting 
- Proposals to add logger level and colors to the logger pattern.
- Use whitespace to improve readability of e.g. Testreport print out.

Change logger pattern and formatting to improve readability of output

---

src/main/java/de/retest/recheck/cli/RecheckCli.java
src/main/java/de/retest/recheck/cli/subcommands/Account.java
src/main/java/de/retest/recheck/cli/utils/HelpColorScheme.java

> Additionally apply custom color scheme to new CommandLine in Account.java 
The custom color scheme was not applied to the command `account` because it creates a new CommandLine-object.
This PR fixes this by adding the custom color scheme in the `run()`-method of `Account.java`.

Add custom color scheme to Account

---

README.md

Update README.md to include Account command
https://github.com/retest/recheck.cli/pull/202

Update README.md to include Account cmd

---

.mergify.yml

This synchronizes mergify to retest/recheck
Please do the following:
1. Verify branch protection rules in place.
2. Mark PR ready for review.
3. Review this PR.
4. Manually merge.

Synchronize mergify with retest/recheck

---

.dependabot/config.yml

which is copied from retest/recheck-web

Add dependabot config to ignore recheck dependency

---

src/main/java/de/retest/recheck/cli/utils/ErrorHandler.java

Fixes a small formatting error

Remove new line before error message

---

src/main/java/de/retest/recheck/cli/subcommands/Show.java

Notify the user about the reason the program ended

Add logger warning in case of invalid filter with --exclude
